#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,		 color1,				 sensorvexiq_colorgrayscale)
#pragma config(Sensor, in2,		 color2,				 sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, in3,		 color3,				 sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, in4,		 color4,				 sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, in6,		 startbtn,				 sensorVexIQ_Touch)
#pragma config(Sensor, dgtl1,	 dist1,					 sensorSONAR_mm)
#pragma config(Sensor, I2C_1,	 enc1,					 sensorQuadEncoderOnI2CPort,		, AutoAssign )
#pragma config(Sensor, I2C_2,	 enc2,					 sensorQuadEncoderOnI2CPort,		, AutoAssign )
#pragma config(Motor,	 port1,						leftmotor,		 tmotorVex393_HBridge, PIDControl, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,	 port2,						rightmotor,		 tmotorVex393_MC29, PIDControl, driveRight, encoderPort, I2C_2)
#pragma config(Motor,	 port5,						rearmotor,		 tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//
#define upbrush port4
#define rotate1 port6

#define brushspeed 127
#define gotime 5000
#define tapecolor 600
#define gospeed 50
#define angletime 545						 //90degree rotate time


void go_front(int time);
void go_rear(int time);
void turn_right(int angle);
void turn_left(int angle);
void set_parrel();
void start_competition();
void ball_isbig();

task brush()
{
	for(;;)
		{
			 motor[rotate1]=127;
		}
}
task ball(){
 for(;;){
 ball_isbig();  
 }	
}
task main()
{
	start_competition();
	startTask(brush);
	startTask(ball);
	while(SensorValue(color3)<tapecolor||SensorValue(color4)<tapecolor)
	{
	go_front(50);
	//ball_isbig();
	}
	while(SensorValue(color1)<tapecolor||SensorValue(color2)<tapecolor)
	{
	go_front(50);
	//ball_isbig();
	}
	while(SensorValue(color3)<tapecolor||SensorValue(color4)<tapecolor)
	{
	go_rear(250);
	//ball_isbig();
	}
	turn_left(90);
	go_front(500);
	turn_right(90);
	while(SensorValue(color1)<tapecolor||SensorValue(color2)<tapecolor)
	{
	go_front(500);
	//ball_isbig();
	}
	turn_left(90);
	go_front(250);
	while(SensorValue(color1)<tapecolor||SensorValue(color2)<tapecolor){
	go_front(800);
	//turn_left(5);
	//turn_right(5);
	//ball_isbig();

	}
	turn_left(90);
	while(SensorValue(color1)<tapecolor||SensorValue(color2)<tapecolor){
	go_front(800);
	ball_isbig();
	}
	turn_right(90);
	go_front(500);
}
void go_front(int time){
resetMotorEncoder(leftMotor);
resetMotorEncoder(rightMotor);
 while(getMotorEncoder(rightMotor) < 50)
	{
		motor[rightMotor] = gospeed;
		motor[leftMotor] = gospeed;
	}

}

void go_rear(int time){
resetMotorEncoder(leftMotor);
resetMotorEncoder(rightMotor);
 while(getMotorEncoder(rightMotor) < 50)
	{
		motor[rightMotor] = -gospeed;
		motor[leftMotor] = -gospeed;
	}

}

void turn_right(int angle){
 clearTimer(T1);
 while(time1[T1]<545 ){
		motor[leftmotor]=gospeed;
		motor[rightmotor]=-gospeed;
		motor[rearmotor]=-gospeed;
	}
	clearTimer(T1);
}
void turn_left(int angle){
	clearTimer(T1);
	while(time1[T1]<545){
		motor[leftmotor]=-gospeed;
		motor[rightmotor]=gospeed;
		motor[rearmotor]=gospeed;
	}
}
void set_parrel(){

	while(sensorvalue(color2)<tapecolor&&sensorvalue(color3)<tapecolor&&sensorvalue(color4)<tapecolor){
		if(sensorvalue(color3)>tapecolor&&sensorValue(color4)<tapecolor){turn_left(15);}
		else if(sensorValue(color3)<tapecolor&&sensorValue(color4)>tapecolor){turn_right(15)}
	}
}
void start_competition()
{
	for(;;)
		{
		while(SensorValue(startbtn) == 0)		// Loop while robot's bumper/touch sensor isn't pressed in
		{
		// Do nothing
		}
			if(SensorValue(startbtn) == 1)
			{
				break;
			}
	 }
}
void ball_isbig(){
if(sensorvalue(dist1)<80){
		motor[upbrush]=127;
		sleep(3000);
	}
}
